name: Auto-Merge

on:
  pull_request_target:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    if: github.event.label.name == 'validation:passed'
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.name 'priyanshbot'
          git config --global user.email '129733067+priyanshbot@users.noreply.github.com'

      - name: Merge PR
        uses: pascalgn/automerge-action@v0.16.2
        env:
          GITHUB_TOKEN: "${{ secrets.BOT_TOKEN }}"
          MERGE_METHOD: "squash"

